# Generated by Django 3.2 on 2022-06-24 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220624_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='fax',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='home',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='idback',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='idcardtype',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='idfront',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='idnumber',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepix',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 8, 31, 7, 663142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txmode',
            field=models.CharField(max_length=500),
        ),
    ]
