# Generated by Django 3.2 on 2022-06-25 00:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220625_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 10, 48, 36, 279332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet'),
        ),
    ]
