# Generated by Django 3.2 on 2022-06-25 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_trade_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 11, 5, 41, 21669, tzinfo=utc)),
        ),
    ]
