# Generated by Django 3.2 on 2022-07-13 23:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_alter_trade_expires_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='trade',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 9, 30, 29, 918698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('isVerified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactype', models.CharField(max_length=300)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('cointobuy', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=300)),
                ('qnt', models.CharField(max_length=300)),
                ('phonenum', models.CharField(max_length=300)),
                ('paymentmethod', models.CharField(max_length=300)),
                ('payselectcoin', models.CharField(blank=True, default='', max_length=100)),
                ('paywalletadd', models.CharField(blank=True, default='', max_length=100)),
                ('paybankname', models.CharField(blank=True, default='', max_length=100)),
                ('payaccname', models.CharField(blank=True, default='', max_length=100)),
                ('payaccnum', models.CharField(blank=True, default='', max_length=100)),
                ('receivingmethod', models.CharField(max_length=300)),
                ('receiveselectcoin', models.CharField(blank=True, default='', max_length=100)),
                ('receivewalletadd', models.CharField(blank=True, default='', max_length=100)),
                ('receivebankname', models.CharField(blank=True, default='', max_length=100)),
                ('receiveaccname', models.CharField(blank=True, default='', max_length=100)),
                ('receiveaccnum', models.CharField(blank=True, default='', max_length=100)),
                ('termsncondition', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
