# Generated by Django 3.2 on 2022-07-16 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220715_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 3, 29, 42, 834688, tzinfo=utc)),
        ),
    ]
